<?php

namespace Database\Seeders;

use App\Models\Equipment;
use App\Models\Laboratory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all laboratories
        $labKimia = Laboratory::where('code', 'LAB-KIM-001')->first();
        $labBio = Laboratory::where('code', 'LAB-BIO-001')->first();
        $labFisika = Laboratory::where('code', 'LAB-FIS-001')->first();
        $labGeo = Laboratory::where('code', 'LAB-GEO-001')->first();
        $labMesin = Laboratory::where('code', 'LAB-TEK-001')->first();
        $labKom = Laboratory::where('code', 'LAB-KOM-001')->first();
        $labFreeze = Laboratory::where('code', 'LAB-KIM-002')->first();

        $equipment = [
            // Laboratorium Kimia Analitik
            [
                'name' => 'FTIR Spectrometer',
                'code' => 'EQ-KIM-001',
                'laboratory_id' => $labKimia?->id,
                'category' => 'analytical',
                'brand' => 'Shimadzu',
                'model' => 'IRPrestige-21',
                'serial_number' => 'A12345678',
                'description' => 'Fourier Transform Infrared Spectrometer untuk analisis struktur molekul organik dan anorganik.',
                'specifications' => [
                    'Wavelength Range' => '7800-350 cm⁻¹',
                    'Resolution' => '0.5 cm⁻¹',
                    'S/N Ratio' => '60,000:1',
                    'Detector' => 'DLATGS',
                ],
                'purchase_date' => '2022-03-15',
                'purchase_price' => 450000000,
                'supplier' => 'PT Shimadzu Indonesia',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2024-03-15',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 90,
                'calibration_interval_days' => 365,
                'location_detail' => 'Ruang Instrumen, Meja 1',
            ],
            [
                'name' => 'GC-MS',
                'code' => 'EQ-KIM-002',
                'laboratory_id' => $labKimia?->id,
                'category' => 'analytical',
                'brand' => 'Agilent',
                'model' => '7890B-5977B',
                'serial_number' => 'US89012345',
                'description' => 'Gas Chromatography-Mass Spectrometry untuk identifikasi senyawa organik volatil.',
                'specifications' => [
                    'Detector' => 'Mass Selective Detector',
                    'Mass Range' => '1.6-1050 m/z',
                    'Sensitivity' => '< 1 pg OFN',
                    'Scan Speed' => '20,000 amu/sec',
                ],
                'purchase_date' => '2021-08-20',
                'purchase_price' => 850000000,
                'supplier' => 'Agilent Technologies',
                'warranty_period' => '3 tahun',
                'warranty_until' => '2024-08-20',
                'condition' => 'good',
                'status' => 'in_use',
                'status_notes' => 'Sedang digunakan untuk penelitian mahasiswa pascasarjana',
                'maintenance_interval_days' => 60,
                'calibration_interval_days' => 180,
                'location_detail' => 'Ruang Instrumen, Meja 3',
            ],
            [
                'name' => 'HPLC',
                'code' => 'EQ-KIM-003',
                'laboratory_id' => $labKimia?->id,
                'category' => 'analytical',
                'brand' => 'Waters',
                'model' => 'Alliance e2695',
                'serial_number' => 'H1234ABC',
                'description' => 'High Performance Liquid Chromatography untuk pemisahan dan analisis senyawa non-volatil.',
                'purchase_date' => '2023-01-10',
                'purchase_price' => 650000000,
                'supplier' => 'Waters Corporation',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2025-01-10',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 90,
                'calibration_interval_days' => 365,
                'location_detail' => 'Ruang Instrumen, Meja 2',
            ],
            [
                'name' => 'Analytical Balance',
                'code' => 'EQ-KIM-004',
                'laboratory_id' => $labKimia?->id,
                'category' => 'measurement',
                'brand' => 'Mettler Toledo',
                'model' => 'XPE205',
                'serial_number' => 'B1908765432',
                'description' => 'Timbangan analitik presisi tinggi untuk penimbangan sampel.',
                'specifications' => [
                    'Readability' => '0.01 mg',
                    'Maximum Capacity' => '220 g',
                    'Repeatability' => '0.015 mg',
                    'Linearity' => '±0.03 mg',
                ],
                'purchase_date' => '2023-05-12',
                'purchase_price' => 85000000,
                'supplier' => 'PT Mettler Toledo Indonesia',
                'warranty_period' => '1 tahun',
                'warranty_until' => '2024-05-12',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 30,
                'calibration_interval_days' => 180,
                'location_detail' => 'Ruang Timbang, Lemari Anti-Getaran',
            ],

            // Laboratorium Biologi Molekuler
            [
                'name' => 'PCR Thermal Cycler',
                'code' => 'EQ-BIO-001',
                'laboratory_id' => $labBio?->id,
                'category' => 'analytical',
                'brand' => 'Bio-Rad',
                'model' => 'T100',
                'serial_number' => 'BR78901234',
                'description' => 'Thermal Cycler untuk amplifikasi DNA dengan teknologi PCR.',
                'specifications' => [
                    'Sample Capacity' => '96 wells (0.2 mL)',
                    'Temperature Range' => '4-100°C',
                    'Ramp Rate' => '≥5°C/s',
                    'Temperature Accuracy' => '±0.25°C',
                ],
                'purchase_date' => '2022-09-15',
                'purchase_price' => 125000000,
                'supplier' => 'Bio-Rad Laboratories',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2024-09-15',
                'condition' => 'good',
                'status' => 'available',
                'maintenance_interval_days' => 90,
                'calibration_interval_days' => 365,
                'location_detail' => 'Ruang PCR, Meja Kerja 1',
            ],
            [
                'name' => 'Laminar Flow Cabinet',
                'code' => 'EQ-BIO-002',
                'laboratory_id' => $labBio?->id,
                'category' => 'safety',
                'brand' => 'Esco',
                'model' => 'Airstream Class II Type A2',
                'serial_number' => 'ESC2023456',
                'description' => 'Biological Safety Cabinet untuk kerja steril dengan mikroorganisme.',
                'specifications' => [
                    'Class' => 'II Type A2',
                    'Width' => '1200 mm',
                    'HEPA Efficiency' => '99.99% at 0.3 μm',
                    'Airflow Velocity' => '0.38 m/s',
                ],
                'purchase_date' => '2021-11-20',
                'purchase_price' => 45000000,
                'supplier' => 'PT Esco Indonesia',
                'warranty_period' => '1 tahun',
                'warranty_until' => '2022-11-20',
                'condition' => 'good',
                'status' => 'available',
                'maintenance_interval_days' => 30,
                'calibration_interval_days' => 180,
                'location_detail' => 'Ruang Kultur, Sudut Kanan',
            ],
            [
                'name' => 'Fluorescence Microscope',
                'code' => 'EQ-BIO-003',
                'laboratory_id' => $labBio?->id,
                'category' => 'analytical',
                'brand' => 'Olympus',
                'model' => 'BX53F',
                'serial_number' => 'OLY9876543',
                'description' => 'Mikroskop fluoresen untuk visualisasi sampel biologis dengan pewarnaan fluoresen.',
                'purchase_date' => '2023-02-28',
                'purchase_price' => 320000000,
                'supplier' => 'Olympus Scientific Solutions',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2025-02-28',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 180,
                'calibration_interval_days' => 365,
                'location_detail' => 'Ruang Mikroskopi, Meja Anti-Getaran',
            ],
            [
                'name' => 'Deep Freezer -80°C',
                'code' => 'EQ-BIO-004',
                'laboratory_id' => $labBio?->id,
                'category' => 'general',
                'brand' => 'Thermo Fisher',
                'model' => 'TSX Series',
                'serial_number' => 'TF2023ULT80',
                'description' => 'Ultra-low temperature freezer untuk penyimpanan sampel biologis jangka panjang.',
                'specifications' => [
                    'Temperature Range' => '-50 to -86°C',
                    'Capacity' => '483 liters',
                    'Interior Material' => 'Stainless Steel',
                    'Alarm System' => 'Audio/Visual',
                ],
                'purchase_date' => '2022-06-10',
                'purchase_price' => 180000000,
                'supplier' => 'Thermo Fisher Scientific',
                'warranty_period' => '3 tahun',
                'warranty_until' => '2025-06-10',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 90,
                'location_detail' => 'Ruang Penyimpanan Sampel',
            ],

            // Laboratorium Fisika Komputasi
            [
                'name' => 'Workstation Computer High-End',
                'code' => 'EQ-FIS-001',
                'laboratory_id' => $labFisika?->id,
                'category' => 'computer',
                'brand' => 'Dell',
                'model' => 'Precision 7920 Tower',
                'serial_number' => 'DELL7920-2023-001',
                'description' => 'Workstation untuk simulasi fisika komputasi dan pemodelan numerik.',
                'specifications' => [
                    'Processor' => 'Intel Xeon Gold 6248R (Dual)',
                    'RAM' => '128 GB DDR4',
                    'GPU' => 'NVIDIA RTX A5000 24GB',
                    'Storage' => '2TB NVMe SSD + 8TB HDD',
                ],
                'purchase_date' => '2023-07-01',
                'purchase_price' => 95000000,
                'supplier' => 'Dell Technologies Indonesia',
                'warranty_period' => '3 tahun on-site',
                'warranty_until' => '2026-07-01',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 180,
                'location_detail' => 'Stasiun Kerja No. 15',
            ],
            [
                'name' => 'Oscilloscope Digital',
                'code' => 'EQ-FIS-002',
                'laboratory_id' => $labFisika?->id,
                'category' => 'measurement',
                'brand' => 'Tektronix',
                'model' => 'TBS2000B',
                'serial_number' => 'TEK2000B789',
                'description' => 'Osiloskop digital untuk pengukuran sinyal elektronik.',
                'specifications' => [
                    'Bandwidth' => '200 MHz',
                    'Channels' => '4',
                    'Sample Rate' => '2 GS/s',
                    'Record Length' => '20 Mpts',
                ],
                'purchase_date' => '2022-04-15',
                'purchase_price' => 35000000,
                'supplier' => 'Tektronix',
                'warranty_period' => '3 tahun',
                'warranty_until' => '2025-04-15',
                'condition' => 'good',
                'status' => 'available',
                'maintenance_interval_days' => 180,
                'calibration_interval_days' => 365,
                'location_detail' => 'Rak Peralatan Elektronik A-3',
            ],

            // Laboratorium Geologi
            [
                'name' => 'Petrographic Microscope',
                'code' => 'EQ-GEO-001',
                'laboratory_id' => $labGeo?->id,
                'category' => 'analytical',
                'brand' => 'Nikon',
                'model' => 'Eclipse LV100N POL',
                'serial_number' => 'NIK-POL-2022-123',
                'description' => 'Mikroskop petrografi untuk analisis sayatan tipis batuan dan mineral.',
                'purchase_date' => '2022-10-05',
                'purchase_price' => 185000000,
                'supplier' => 'Nikon Instruments',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2024-10-05',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 180,
                'calibration_interval_days' => 365,
                'location_detail' => 'Ruang Mikroskopi Geologi, Meja 2',
            ],
            [
                'name' => 'X-Ray Diffractometer (XRD)',
                'code' => 'EQ-GEO-002',
                'laboratory_id' => $labGeo?->id,
                'category' => 'analytical',
                'brand' => 'Rigaku',
                'model' => 'MiniFlex 600',
                'serial_number' => 'RIG-XRD-600-789',
                'description' => 'Difraktometer sinar-X untuk analisis struktur kristal mineral.',
                'specifications' => [
                    'X-ray Source' => 'Cu Kα (40 kV, 15 mA)',
                    'Detector' => 'D/teX Ultra2',
                    'Goniometer' => 'θ/2θ',
                    'Angular Range' => '2θ = -3° to 145°',
                ],
                'purchase_date' => '2021-12-12',
                'purchase_price' => 550000000,
                'supplier' => 'Rigaku Corporation',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2023-12-12',
                'condition' => 'good',
                'status' => 'maintenance',
                'status_notes' => 'Sedang dilakukan maintenance rutin X-ray tube',
                'maintenance_interval_days' => 90,
                'calibration_interval_days' => 180,
                'location_detail' => 'Ruang Instrumen XRD',
            ],
            [
                'name' => 'Rock Grinding Machine',
                'code' => 'EQ-GEO-003',
                'laboratory_id' => $labGeo?->id,
                'category' => 'preparation',
                'brand' => 'Buehler',
                'model' => 'PetroThin',
                'serial_number' => 'BUE-PT-456',
                'description' => 'Mesin grinding untuk preparasi sayatan tipis batuan.',
                'purchase_date' => '2020-08-20',
                'purchase_price' => 65000000,
                'supplier' => 'Buehler ITW',
                'warranty_period' => '1 tahun',
                'warranty_until' => '2021-08-20',
                'condition' => 'fair',
                'status' => 'available',
                'maintenance_interval_days' => 30,
                'location_detail' => 'Workshop Preparasi Sampel',
            ],

            // Laboratorium Teknik Mesin
            [
                'name' => 'CNC Milling Machine',
                'code' => 'EQ-TEK-001',
                'laboratory_id' => $labMesin?->id,
                'category' => 'general',
                'brand' => 'Haas',
                'model' => 'VF-2',
                'serial_number' => 'HAAS-VF2-2022-345',
                'description' => 'Mesin CNC milling untuk praktikum manufaktur dan machining.',
                'specifications' => [
                    'X-axis Travel' => '762 mm',
                    'Y-axis Travel' => '406 mm',
                    'Z-axis Travel' => '508 mm',
                    'Spindle Speed' => '8,100 RPM',
                ],
                'purchase_date' => '2022-05-18',
                'purchase_price' => 650000000,
                'supplier' => 'Haas Automation',
                'warranty_period' => '1 tahun',
                'warranty_until' => '2023-05-18',
                'condition' => 'good',
                'status' => 'available',
                'maintenance_interval_days' => 60,
                'calibration_interval_days' => 180,
                'location_detail' => 'Area Machining CNC, Zona A',
            ],
            [
                'name' => 'Universal Testing Machine',
                'code' => 'EQ-TEK-002',
                'laboratory_id' => $labMesin?->id,
                'category' => 'measurement',
                'brand' => 'Instron',
                'model' => '5985',
                'serial_number' => 'INST-5985-2023-12',
                'description' => 'Mesin uji tarik universal untuk pengujian kekuatan material.',
                'specifications' => [
                    'Load Capacity' => '250 kN',
                    'Crosshead Speed Range' => '0.001-500 mm/min',
                    'Load Accuracy' => '±0.5%',
                    'Extension Accuracy' => '±0.5%',
                ],
                'purchase_date' => '2023-03-22',
                'purchase_price' => 485000000,
                'supplier' => 'Instron',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2025-03-22',
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 90,
                'calibration_interval_days' => 365,
                'location_detail' => 'Ruang Pengujian Material',
            ],
            [
                'name' => 'Lathe Machine Manual',
                'code' => 'EQ-TEK-003',
                'laboratory_id' => $labMesin?->id,
                'category' => 'general',
                'brand' => 'Graziano',
                'model' => 'SAG 210',
                'serial_number' => 'GRAZ-210-2019-45',
                'description' => 'Mesin bubut manual untuk praktikum pemesinan dasar.',
                'purchase_date' => '2019-06-10',
                'purchase_price' => 120000000,
                'supplier' => 'PT Graziano Indonesia',
                'warranty_period' => '1 tahun',
                'warranty_until' => '2020-06-10',
                'condition' => 'fair',
                'status' => 'available',
                'maintenance_interval_days' => 30,
                'location_detail' => 'Workshop Area, Baris 2 No. 5',
            ],

            // Laboratorium Jaringan Komputer
            [
                'name' => 'Network Simulator Rack',
                'code' => 'EQ-KOM-001',
                'laboratory_id' => $labKom?->id,
                'category' => 'computer',
                'brand' => 'Cisco',
                'model' => 'Catalyst 9300 Series',
                'serial_number' => 'CSC-9300-2023-789',
                'description' => 'Switch Cisco untuk praktikum jaringan komputer dan routing.',
                'specifications' => [
                    'Ports' => '48x 1G + 4x 10G SFP+',
                    'Stacking' => 'StackWise-480',
                    'Throughput' => '176 Gbps',
                    'Features' => 'Layer 3, PoE+, UADP 2.0',
                ],
                'purchase_date' => '2023-08-15',
                'purchase_price' => 85000000,
                'supplier' => 'Cisco Systems Indonesia',
                'warranty_period' => 'Lifetime',
                'warranty_until' => null,
                'condition' => 'excellent',
                'status' => 'available',
                'maintenance_interval_days' => 180,
                'location_detail' => 'Server Rack A, U10-U15',
            ],
            [
                'name' => 'Server Dell PowerEdge',
                'code' => 'EQ-KOM-002',
                'laboratory_id' => $labKom?->id,
                'category' => 'computer',
                'brand' => 'Dell',
                'model' => 'PowerEdge R750',
                'serial_number' => 'DELL-R750-2023-456',
                'description' => 'Server untuk praktikum administrasi sistem dan virtualisasi.',
                'specifications' => [
                    'Processor' => 'Intel Xeon Silver 4314 (Dual)',
                    'RAM' => '256 GB DDR4',
                    'Storage' => '8x 2TB SAS HDD RAID 10',
                    'Network' => '4x 10GbE SFP+',
                ],
                'purchase_date' => '2023-09-01',
                'purchase_price' => 145000000,
                'supplier' => 'Dell Technologies Indonesia',
                'warranty_period' => '3 tahun ProSupport',
                'warranty_until' => '2026-09-01',
                'condition' => 'excellent',
                'status' => 'in_use',
                'status_notes' => 'Menjalankan VMs untuk praktikum semester ini',
                'maintenance_interval_days' => 90,
                'location_detail' => 'Server Room, Rack B, U20-U22',
            ],

            // Laboratorium Freeze Dryer
            [
                'name' => 'Freeze Dryer Industrial',
                'code' => 'EQ-KIM-005',
                'laboratory_id' => $labFreeze?->id,
                'category' => 'analytical',
                'brand' => 'Christ',
                'model' => 'Alpha 2-4 LDplus',
                'serial_number' => 'CHR-A24LD-2021-123',
                'description' => 'Freeze dryer skala industri untuk liofilisasi sampel biologis, farmasi, dan makanan.',
                'specifications' => [
                    'Condenser Temperature' => '-85°C',
                    'Ice Capacity' => '4 kg/24h',
                    'Vacuum' => '0.01 mbar',
                    'Shelf Area' => '0.36 m²',
                ],
                'purchase_date' => '2021-07-15',
                'purchase_price' => 750000000,
                'supplier' => 'Martin Christ Germany',
                'warranty_period' => '2 tahun',
                'warranty_until' => '2023-07-15',
                'condition' => 'good',
                'status' => 'calibration',
                'status_notes' => 'Sedang dilakukan kalibrasi dan maintenance rutin bulanan',
                'maintenance_interval_days' => 30,
                'calibration_interval_days' => 180,
                'location_detail' => 'Ruang Freeze Dryer Utama',
            ],
            [
                'name' => 'Vacuum Pump Oil Rotary',
                'code' => 'EQ-KIM-006',
                'laboratory_id' => $labFreeze?->id,
                'category' => 'general',
                'brand' => 'Edwards',
                'model' => 'RV12',
                'serial_number' => 'EDW-RV12-2021-456',
                'description' => 'Pompa vakum untuk sistem freeze dryer.',
                'specifications' => [
                    'Pumping Speed' => '12 m³/h',
                    'Ultimate Pressure' => '2 x 10⁻³ mbar',
                    'Motor Power' => '0.75 kW',
                    'Oil Capacity' => '1.0 liter',
                ],
                'purchase_date' => '2021-07-15',
                'purchase_price' => 45000000,
                'supplier' => 'Edwards Vacuum',
                'warranty_period' => '1 tahun',
                'warranty_until' => '2022-07-15',
                'condition' => 'good',
                'status' => 'available',
                'maintenance_interval_days' => 30,
                'location_detail' => 'Ruang Utilitas Freeze Dryer',
            ],
        ];

        foreach ($equipment as $item) {
            Equipment::create($item);
        }
    }
}
