<?php

namespace Database\Seeders;

use App\Models\Reagent;
use App\Models\Laboratory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ReagentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lab = Laboratory::first();

        if (!$lab) {
            $this->command->warn('No laboratory found. Please seed laboratories first.');
            return;
        }

        $reagents = [
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-001',
                'name' => 'Asam Sulfat (H₂SO₄)',
                'cas_number' => '7664-93-9',
                'formula' => 'H₂SO₄',
                'category' => 'acid',
                'grade' => 'AR (Analytical Reagent)',
                'quantity' => 2500.00,
                'unit' => 'mL',
                'hazard_class' => 'corrosive',
                'storage_location' => 'Lemari Asam - A1',
                'storage_condition' => 'special',
                'status' => 'available',
                'min_stock_level' => 500.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'K49632145',
                'catalog_number' => '100731',
                'purchase_date' => Carbon::now()->subMonths(6),
                'opened_date' => Carbon::now()->subMonths(5),
                'expiry_date' => Carbon::now()->addYears(2),
                'price' => 485000,
                'description' => 'Asam sulfat pekat 95-98% untuk analisis kimia',
                'usage_instructions' => "- Selalu gunakan APD lengkap (lab coat, sarung tangan, kacamata safety, face shield)\n- Tambahkan asam ke air, JANGAN sebaliknya\n- Gunakan di dalam fume hood\n- Hindari kontak dengan kulit dan mata",
                'disposal_instructions' => "- Netralkan dengan NaOH/Na₂CO₃ secara perlahan\n- Encerkan hingga pH 6-8\n- Buang ke sistem pembuangan limbah laboratorium\n- Jangan langsung ke saluran air",
                'safety_notes' => "SANGAT KOROSIF! Dapat menyebabkan luka bakar parah. Reaksi eksotermis dengan air. Hindari kontak dengan bahan organik.",
                'notes' => 'Simpan di area berventilasi baik, jauh dari bahan organik dan logam',
            ],
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-002',
                'name' => 'Natrium Hidroksida (NaOH)',
                'cas_number' => '1310-73-2',
                'formula' => 'NaOH',
                'category' => 'base',
                'grade' => 'PA (Pro Analysis)',
                'quantity' => 1500.00,
                'unit' => 'g',
                'hazard_class' => 'corrosive',
                'storage_location' => 'Lemari Basa - B2',
                'storage_condition' => 'room_temperature',
                'status' => 'available',
                'min_stock_level' => 500.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'A0423856',
                'catalog_number' => '106498',
                'purchase_date' => Carbon::now()->subMonths(4),
                'opened_date' => Carbon::now()->subMonths(3),
                'expiry_date' => Carbon::now()->addYears(3),
                'price' => 325000,
                'description' => 'Natrium hidroksida pellet untuk titrasi dan preparasi larutan basa',
                'usage_instructions' => "- Gunakan APD lengkap\n- Timbang dengan cepat (higroskopis)\n- Larutkan dalam air dingin secara perlahan\n- Hindari kontak dengan CO₂",
                'disposal_instructions' => "- Netralkan dengan HCl encer\n- Encerkan hingga pH 6-8\n- Buang ke sistem pembuangan limbah laboratorium",
                'safety_notes' => "SANGAT KOROSIF! Higroskopis. Dapat menyebabkan luka bakar parah pada kulit dan kerusakan mata permanen.",
                'notes' => 'Simpan dalam wadah tertutup rapat, hindari paparan udara lembab',
            ],
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-003',
                'name' => 'Etanol Absolute',
                'cas_number' => '64-17-5',
                'formula' => 'C₂H₅OH',
                'category' => 'solvent',
                'grade' => 'AR 99.9%',
                'quantity' => 5000.00,
                'unit' => 'mL',
                'hazard_class' => 'flammable',
                'storage_location' => 'Lemari Flammable - F1',
                'storage_condition' => 'room_temperature',
                'status' => 'available',
                'min_stock_level' => 1000.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'K50142789',
                'catalog_number' => '100983',
                'purchase_date' => Carbon::now()->subMonths(2),
                'opened_date' => Carbon::now()->subMonths(1),
                'expiry_date' => Carbon::now()->addYears(2),
                'price' => 650000,
                'description' => 'Etanol absolute untuk ekstraksi, analisis, dan pelarut organik',
                'usage_instructions' => "- Gunakan di area berventilasi baik atau fume hood\n- Jauhkan dari sumber panas dan api\n- Gunakan APD standar\n- Tutup rapat setelah digunakan",
                'disposal_instructions' => "- Kumpulkan limbah etanol terpisah\n- Dapat didaur ulang dengan distilasi\n- Atau buang ke container limbah solvent organik",
                'safety_notes' => "MUDAH TERBAKAR! Uap dapat membentuk campuran eksplosif dengan udara. Hindari sumber api dan percikan.",
                'notes' => 'Simpan di lemari khusus flammable, jauh dari oksidator dan sumber panas',
            ],
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-004',
                'name' => 'Asam Klorida (HCl)',
                'cas_number' => '7647-01-0',
                'formula' => 'HCl',
                'category' => 'acid',
                'grade' => 'AR 37%',
                'quantity' => 3000.00,
                'unit' => 'mL',
                'hazard_class' => 'corrosive',
                'storage_location' => 'Lemari Asam - A2',
                'storage_condition' => 'special',
                'status' => 'available',
                'min_stock_level' => 750.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'HC1092456',
                'catalog_number' => '100317',
                'purchase_date' => Carbon::now()->subMonths(5),
                'opened_date' => Carbon::now()->subMonths(4),
                'expiry_date' => Carbon::now()->addYears(3),
                'price' => 380000,
                'description' => 'Asam klorida pekat untuk analisis dan preparasi larutan',
                'usage_instructions' => "- Gunakan di fume hood\n- APD lengkap wajib (termasuk face shield)\n- Tambahkan asam ke air saat mengencerkan\n- Hindari menghirup uap",
                'disposal_instructions' => "- Netralkan dengan Na₂CO₃ atau NaOH encer\n- Encerkan hingga pH netral\n- Buang ke sistem pembuangan limbah laboratorium",
                'safety_notes' => "SANGAT KOROSIF! Uap dapat menyebabkan iritasi saluran pernapasan. Bereaksi dengan logam menghasilkan gas H₂ (mudah terbakar).",
                'notes' => 'Simpan di area berventilasi baik, botol dalam posisi tegak',
            ],
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-005',
                'name' => 'Fenolftalein Indikator',
                'cas_number' => '77-09-8',
                'formula' => 'C₂₀H₁₄O₄',
                'category' => 'indicator',
                'grade' => 'AR',
                'quantity' => 100.00,
                'unit' => 'g',
                'hazard_class' => 'non_hazardous',
                'storage_location' => 'Lemari Indikator - I1',
                'storage_condition' => 'room_temperature',
                'status' => 'available',
                'min_stock_level' => 25.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'PH2034567',
                'catalog_number' => '107233',
                'purchase_date' => Carbon::now()->subMonths(8),
                'opened_date' => Carbon::now()->subMonths(7),
                'expiry_date' => Carbon::now()->addYears(4),
                'price' => 425000,
                'description' => 'Indikator asam-basa, tidak berwarna di pH <8.2, merah muda di pH >10',
                'usage_instructions' => "- Larutkan dalam etanol 70% (1% w/v)\n- Gunakan 2-3 tetes untuk titrasi asam-basa\n- Simpan larutan dalam botol coklat\n- Hindari paparan cahaya langsung",
                'disposal_instructions' => "- Encerkan dengan air\n- Buang ke limbah organik laboratorium",
                'safety_notes' => "Relatif aman. Gunakan APD standar laboratorium.",
                'notes' => 'Simpan dalam wadah tertutup rapat, hindari cahaya dan kelembaban',
            ],
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-006',
                'name' => 'Kalium Dikromat (K₂Cr₂O₇)',
                'cas_number' => '7778-50-9',
                'formula' => 'K₂Cr₂O₇',
                'category' => 'oxidizing',
                'grade' => 'AR',
                'quantity' => 450.00,
                'unit' => 'g',
                'hazard_class' => 'oxidizing',
                'storage_location' => 'Lemari Oksidator - O1',
                'storage_condition' => 'room_temperature',
                'status' => 'low_stock',
                'min_stock_level' => 500.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'KD3045789',
                'catalog_number' => '104864',
                'purchase_date' => Carbon::now()->subMonths(10),
                'opened_date' => Carbon::now()->subMonths(9),
                'expiry_date' => Carbon::now()->addYears(5),
                'price' => 785000,
                'description' => 'Agen oksidasi kuat untuk analisis COD dan titrasi',
                'usage_instructions' => "- Gunakan APD lengkap\n- Hindari kontak dengan bahan organik dan reduktor\n- Gunakan spatula bersih dan kering\n- Timbang dengan hati-hati",
                'disposal_instructions' => "- Reduksi dengan Na₂S₂O₃ atau FeSO₄\n- Endapkan kromium sebagai Cr(OH)₃\n- Buang ke container limbah B3\n- JANGAN buang langsung ke saluran air",
                'safety_notes' => "OKSIDATOR KUAT! KARSINOGENIK! Dapat menyebabkan kanker. Hindari menghirup debu. Dapat menyebabkan iritasi kulit dan mata parah.",
                'notes' => 'BAHAN BERBAHAYA! Simpan terpisah dari bahan organik dan reduktor. Catat penggunaan dengan ketat.',
            ],
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-007',
                'name' => 'Natrium Klorida (NaCl)',
                'cas_number' => '7647-14-5',
                'formula' => 'NaCl',
                'category' => 'salt',
                'grade' => 'PA',
                'quantity' => 5000.00,
                'unit' => 'g',
                'hazard_class' => 'non_hazardous',
                'storage_location' => 'Lemari Umum - U3',
                'storage_condition' => 'room_temperature',
                'status' => 'available',
                'min_stock_level' => 1000.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'NC5067234',
                'catalog_number' => '106404',
                'purchase_date' => Carbon::now()->subMonths(3),
                'opened_date' => Carbon::now()->subMonths(2),
                'expiry_date' => null,
                'price' => 150000,
                'description' => 'Natrium klorida untuk preparasi larutan buffer dan media',
                'usage_instructions' => "- Gunakan spatula bersih dan kering\n- Timbang sesuai kebutuhan\n- Dapat dilarutkan dalam air\n- APD standar",
                'disposal_instructions' => "- Aman untuk dibuang ke saluran air dengan pengenceran\n- Atau kumpulkan untuk disposal waste umum",
                'safety_notes' => "Relatif aman. Tidak berbahaya dalam kondisi normal.",
                'notes' => 'Simpan dalam wadah tertutup rapat untuk mencegah kontaminasi',
            ],
            [
                'laboratory_id' => $lab->id,
                'code' => 'REG-2025-008',
                'name' => 'Asetonitril (CH₃CN)',
                'cas_number' => '75-05-8',
                'formula' => 'CH₃CN',
                'category' => 'solvent',
                'grade' => 'HPLC Grade',
                'quantity' => 800.00,
                'unit' => 'mL',
                'hazard_class' => 'flammable',
                'storage_location' => 'Lemari Flammable - F2',
                'storage_condition' => 'room_temperature',
                'status' => 'in_use',
                'min_stock_level' => 500.00,
                'manufacturer' => 'Merck KGaA',
                'supplier' => 'PT Brataco',
                'lot_number' => 'ACN8923456',
                'catalog_number' => '100030',
                'purchase_date' => Carbon::now()->subMonths(1),
                'opened_date' => Carbon::now()->subDays(15),
                'expiry_date' => Carbon::now()->addYears(2),
                'price' => 1250000,
                'description' => 'Asetonitril HPLC grade untuk analisis kromatografi',
                'usage_instructions' => "- Gunakan HANYA di area berventilasi baik\n- Hindari sumber panas dan api\n- APD lengkap wajib\n- Tutup rapat segera setelah digunakan\n- Jangan menghirup uap",
                'disposal_instructions' => "- Kumpulkan limbah di container khusus solvent HPLC\n- Dapat didaur ulang dengan distilasi\n- JANGAN buang ke saluran air",
                'safety_notes' => "SANGAT MUDAH TERBAKAR! BERACUN! Dapat diserap melalui kulit. Uap beracun. Hindari kontak dan inhalasi.",
                'notes' => 'Simpan di lemari flammable terpisah, botol dalam posisi tegak. Catat setiap penggunaan.',
            ],
        ];

        foreach ($reagents as $reagentData) {
            Reagent::create($reagentData);
        }

        $this->command->info('Reagent seeder completed successfully. Created 8 reagents.');
    }
}
