<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\Laboratory;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all laboratories
        $laboratories = Laboratory::all();

        if ($laboratories->isEmpty()) {
            $this->command->warn('No laboratories found. Please seed laboratories first.');
            return;
        }

        $services = [
            // KIMIA (8 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-001',
                'name' => 'Analisis GC-MS (Gas Chromatography-Mass Spectrometry)',
                'description' => 'Analisis kualitatif dan kuantitatif senyawa organik volatile dan semi-volatile menggunakan GC-MS.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Organik',
                'method' => 'AOAC 991.14, EPA 8270',
                'duration_days' => 5,
                'price_internal' => 250000,
                'price_external_edu' => 375000,
                'price_external' => 500000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel minimal 10 mL untuk liquid atau 5g untuk solid', 'Form permohonan lengkap', 'MSDS jika bahan berbahaya'],
                'equipment_needed' => [1, 2],
                'sample_preparation' => 'Sampel harus dalam kondisi bersih, bebas partikel tersuspensi. Untuk sampel padat, harap dihaluskan terlebih dahulu.',
                'deliverables' => ['Laporan hasil analisis PDF', 'Chromatogram', 'Spektra massa', 'Raw data'],
                'min_sample' => 1,
                'max_sample' => 10,
                'is_active' => true,
                'popularity' => 45,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-002',
                'name' => 'Analisis HPLC (High Performance Liquid Chromatography)',
                'description' => 'Pemisahan dan analisis senyawa non-volatile menggunakan HPLC dengan berbagai detektor.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Organik',
                'method' => 'USP, ISO 11289',
                'duration_days' => 4,
                'price_internal' => 200000,
                'price_external_edu' => 300000,
                'price_external' => 400000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel minimal 5 mL', 'Informasi senyawa target', 'Standar referensi (jika ada)'],
                'equipment_needed' => [3],
                'sample_preparation' => 'Sampel harus difilter menggunakan syringe filter 0.45 μm sebelum injeksi.',
                'deliverables' => ['Laporan analisis lengkap', 'Chromatogram', 'Data kuantitatif', 'Validasi metode'],
                'min_sample' => 1,
                'max_sample' => 15,
                'is_active' => true,
                'popularity' => 38,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-003',
                'name' => 'Analisis AAS (Atomic Absorption Spectroscopy)',
                'description' => 'Penentuan konsentrasi logam berat dan elemen anorganik dalam sampel.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Anorganik',
                'method' => 'SNI 06-6989.16-2009, APHA 3111',
                'duration_days' => 3,
                'price_internal' => 150000,
                'price_external_edu' => 225000,
                'price_external' => 300000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel minimal 50 mL untuk liquid', 'Informasi matriks sampel', 'Target elemen yang akan dianalisis'],
                'equipment_needed' => [4],
                'sample_preparation' => 'Sampel harus dalam kondisi asam (pH < 2) dengan HNO3 untuk preservasi. Untuk sampel padat perlu destruksi terlebih dahulu.',
                'deliverables' => ['Laporan konsentrasi logam', 'Kurva kalibrasi', 'QC data', 'Certificate of Analysis'],
                'min_sample' => 1,
                'max_sample' => 20,
                'is_active' => true,
                'popularity' => 52,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-004',
                'name' => 'Analisis FTIR (Fourier Transform Infrared Spectroscopy)',
                'description' => 'Identifikasi gugus fungsi dan struktur molekul senyawa organik.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Struktural',
                'method' => 'ASTM E1252',
                'duration_days' => 2,
                'price_internal' => 100000,
                'price_external_edu' => 150000,
                'price_external' => 200000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel minimal 10 mg untuk solid atau 1 mL untuk liquid', 'Sampel murni atau informasi kemurnian'],
                'equipment_needed' => [5],
                'sample_preparation' => 'Sampel padat dapat dianalisis langsung dengan ATR atau dibuat pelet KBr. Liquid dianalisis dengan sel liquid.',
                'deliverables' => ['Spektra FTIR', 'Interpretasi peak', 'Library matching', 'Laporan analisis'],
                'min_sample' => 1,
                'max_sample' => 30,
                'is_active' => true,
                'popularity' => 67,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-005',
                'name' => 'Analisis UV-Vis Spectrophotometry',
                'description' => 'Penentuan konsentrasi senyawa berdasarkan absorbansi cahaya UV-Visible.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Kuantitatif',
                'method' => 'USP 857, AOAC 973.41',
                'duration_days' => 2,
                'price_internal' => 80000,
                'price_external_edu' => 120000,
                'price_external' => 160000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel minimal 3 mL', 'Informasi panjang gelombang maksimum (jika diketahui)'],
                'equipment_needed' => [6],
                'sample_preparation' => 'Sampel harus jernih, bebas partikel tersuspensi. Pengenceran sesuai range absorbansi 0.2-0.8.',
                'deliverables' => ['Spektra UV-Vis', 'Data absorbansi', 'Konsentrasi', 'Kurva kalibrasi'],
                'min_sample' => 1,
                'max_sample' => 25,
                'is_active' => true,
                'popularity' => 43,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-006',
                'name' => 'Titrasi (Asam-Basa, Redoks, Kompleksometri)',
                'description' => 'Penentuan konsentrasi larutan melalui titrasi volumetrik berbagai metode.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Volumetrik',
                'method' => 'SNI, AOAC Official Method',
                'duration_days' => 1,
                'price_internal' => 50000,
                'price_external_edu' => 75000,
                'price_external' => 100000,
                'urgent_surcharge_percent' => 30,
                'requirements' => ['Sampel minimal 25 mL', 'Informasi jenis titrasi yang diinginkan', 'Estimasi konsentrasi'],
                'equipment_needed' => [7],
                'sample_preparation' => 'Sampel harus homogen dan dalam bentuk larutan. Untuk sampel padat perlu dilarutkan terlebih dahulu.',
                'deliverables' => ['Hasil konsentrasi', 'Data titrasi', 'Perhitungan lengkap', 'Laporan singkat'],
                'min_sample' => 1,
                'max_sample' => 50,
                'is_active' => true,
                'popularity' => 29,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-007',
                'name' => 'Analisis ICP-MS (Inductively Coupled Plasma-Mass Spectrometry)',
                'description' => 'Analisis multi-elemen dengan sensitivitas tinggi hingga level ppb-ppt.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Anorganik',
                'method' => 'EPA 6020B, ISO 17294-2',
                'duration_days' => 7,
                'price_internal' => 500000,
                'price_external_edu' => 750000,
                'price_external' => 1000000,
                'urgent_surcharge_percent' => 60,
                'requirements' => ['Sampel minimal 50 mL', 'Daftar elemen target', 'Informasi matriks detail', 'Destruksi sampel (jika padat)'],
                'equipment_needed' => [8],
                'sample_preparation' => 'Sampel harus dalam bentuk larutan asam (2% HNO3). Sampel padat harus melalui destruksi microwave terlebih dahulu.',
                'deliverables' => ['Konsentrasi multi-elemen', 'Spektra massa', 'QC report', 'Method validation', 'CoA'],
                'min_sample' => 1,
                'max_sample' => 8,
                'is_active' => true,
                'popularity' => 34,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-CHEM-008',
                'name' => 'Analisis NMR (Nuclear Magnetic Resonance)',
                'description' => 'Elucidasi struktur molekul organik dengan 1H-NMR dan 13C-NMR.',
                'category' => 'kimia',
                'subcategory' => 'Analisis Struktural',
                'method' => 'ASTM E386',
                'duration_days' => 5,
                'price_internal' => 400000,
                'price_external_edu' => 600000,
                'price_external' => 800000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel minimal 5 mg', 'Sampel murni (>95%)', 'Informasi solvent NMR yang diinginkan'],
                'equipment_needed' => [9],
                'sample_preparation' => 'Sampel dilarutkan dalam deuterated solvent (CDCl3, DMSO-d6, D2O, dll). Konsentrasi 5-20 mg/mL.',
                'deliverables' => ['Spektra 1H-NMR', 'Spektra 13C-NMR', 'Interpretasi peak', 'Raw FID data', 'Chemical shift assignment'],
                'min_sample' => 1,
                'max_sample' => 5,
                'is_active' => true,
                'popularity' => 28,
            ],

            // BIOLOGI (4 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-BIO-001',
                'name' => 'Isolasi dan Ekstraksi DNA',
                'description' => 'Ekstraksi DNA genomik dari berbagai jenis sampel biologis (darah, jaringan, tanaman).',
                'category' => 'biologi',
                'subcategory' => 'Biologi Molekuler',
                'method' => 'Kit Extraction Method, Phenol-Chloroform',
                'duration_days' => 3,
                'price_internal' => 150000,
                'price_external_edu' => 225000,
                'price_external' => 300000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel segar atau frozen', 'Minimal 100 mg tissue atau 200 μL darah', 'Informed consent (untuk sampel manusia)'],
                'equipment_needed' => [10, 11],
                'sample_preparation' => 'Sampel harus dalam kondisi segar atau disimpan -80°C. Hindari freeze-thaw berulang.',
                'deliverables' => ['DNA murni', 'Hasil kuantifikasi (Nanodrop)', 'Elektroforesis gel', 'Laporan konsentrasi dan kemurnian'],
                'min_sample' => 1,
                'max_sample' => 24,
                'is_active' => true,
                'popularity' => 41,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-BIO-002',
                'name' => 'PCR dan Elektroforesis',
                'description' => 'Amplifikasi DNA target menggunakan PCR dan visualisasi dengan gel elektroforesis.',
                'category' => 'biologi',
                'subcategory' => 'Biologi Molekuler',
                'method' => 'Conventional PCR',
                'duration_days' => 2,
                'price_internal' => 120000,
                'price_external_edu' => 180000,
                'price_external' => 240000,
                'urgent_surcharge_percent' => 40,
                'requirements' => ['Template DNA', 'Informasi primer sequence (atau gen target)', 'Estimated PCR product size'],
                'equipment_needed' => [12, 13],
                'sample_preparation' => 'DNA template dengan konsentrasi 10-100 ng/μL, kemurnian A260/280 = 1.8-2.0.',
                'deliverables' => ['Foto gel elektroforesis', 'PCR product', 'Laporan hasil amplifikasi', 'Protokol PCR yang digunakan'],
                'min_sample' => 1,
                'max_sample' => 30,
                'is_active' => true,
                'popularity' => 55,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-BIO-003',
                'name' => 'Uji Aktivitas Antioksidan (DPPH, FRAP)',
                'description' => 'Penentuan aktivitas antioksidan ekstrak menggunakan metode DPPH dan FRAP.',
                'category' => 'biologi',
                'subcategory' => 'Bioassay',
                'method' => 'DPPH Free Radical Scavenging, FRAP Assay',
                'duration_days' => 3,
                'price_internal' => 100000,
                'price_external_edu' => 150000,
                'price_external' => 200000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Ekstrak minimal 5 mL atau 1 g powder', 'Informasi konsentrasi ekstrak', 'Kontrol positif (jika ada)'],
                'equipment_needed' => [14],
                'sample_preparation' => 'Ekstrak dalam solvent yang sesuai (ethanol, methanol, atau aqueous). Konsentrasi 100-1000 ppm.',
                'deliverables' => ['IC50 value', 'Kurva inhibisi', 'Perbandingan dengan standar', 'Laporan lengkap'],
                'min_sample' => 1,
                'max_sample' => 20,
                'is_active' => true,
                'popularity' => 48,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-BIO-004',
                'name' => 'Uji Sitotoksisitas MTT Assay',
                'description' => 'Evaluasi efek sitotoksik senyawa terhadap sel kultur menggunakan MTT assay.',
                'category' => 'biologi',
                'subcategory' => 'Cell Culture & Assay',
                'method' => 'MTT (3-(4,5-dimethylthiazol-2-yl)-2,5-diphenyltetrazolium bromide) Assay',
                'duration_days' => 5,
                'price_internal' => 300000,
                'price_external_edu' => 450000,
                'price_external' => 600000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel senyawa minimal 10 mg', 'Informasi solubilitas', 'Pilihan cell line (akan dikonfirmasi ketersediaan)'],
                'equipment_needed' => [15, 16],
                'sample_preparation' => 'Senyawa harus larut dalam DMSO (<1% final concentration) atau media kultur. Steril atau dapat disterilkan.',
                'deliverables' => ['IC50 value', 'Dose-response curve', 'Cell viability data', 'Grafik dan interpretasi', 'Full report'],
                'min_sample' => 1,
                'max_sample' => 10,
                'is_active' => true,
                'popularity' => 36,
            ],

            // FISIKA (3 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-PHYS-001',
                'name' => 'Karakterisasi XRD (X-Ray Diffraction)',
                'description' => 'Analisis struktur kristal, identifikasi fase, dan ukuran kristal material.',
                'category' => 'fisika',
                'subcategory' => 'Material Characterization',
                'method' => 'ICDD PDF Database, Rietveld Refinement',
                'duration_days' => 4,
                'price_internal' => 200000,
                'price_external_edu' => 300000,
                'price_external' => 400000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel powder minimal 1 g', 'Informasi material (jika diketahui)', 'Safety data sheet'],
                'equipment_needed' => [17],
                'sample_preparation' => 'Sampel harus dalam bentuk powder halus (<63 μm). Homogenkan dengan grinding jika perlu.',
                'deliverables' => ['Diffraktogram', 'Phase identification', 'Crystallite size calculation', 'Lattice parameters', 'Full analysis report'],
                'min_sample' => 1,
                'max_sample' => 15,
                'is_active' => true,
                'popularity' => 39,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-PHYS-002',
                'name' => 'Analisis SEM-EDX (Scanning Electron Microscopy)',
                'description' => 'Pencitraan morfologi permukaan dan analisis komposisi elemen dengan SEM-EDX.',
                'category' => 'fisika',
                'subcategory' => 'Microscopy',
                'method' => 'ASTM E1508, ISO 22309',
                'duration_days' => 5,
                'price_internal' => 350000,
                'price_external_edu' => 525000,
                'price_external' => 700000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel solid maksimal 1 cm³', 'Sampel harus kering dan stabil di vacuum', 'Sampel konduktif atau dapat di-coating'],
                'equipment_needed' => [18],
                'sample_preparation' => 'Sampel mounting pada stub dengan carbon tape. Non-conductive samples perlu gold/carbon coating.',
                'deliverables' => ['SEM images (berbagai magnifikasi)', 'EDX spectrum', 'Elemental mapping', 'Quantitative analysis', 'Full report'],
                'min_sample' => 1,
                'max_sample' => 8,
                'is_active' => true,
                'popularity' => 61,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-PHYS-003',
                'name' => 'Pengujian Sifat Mekanik (Tensile, Hardness)',
                'description' => 'Pengujian kekuatan tarik, kekerasan, dan sifat mekanik material.',
                'category' => 'fisika',
                'subcategory' => 'Mechanical Testing',
                'method' => 'ASTM D638, ASTM E18, ISO 527',
                'duration_days' => 3,
                'price_internal' => 180000,
                'price_external_edu' => 270000,
                'price_external' => 360000,
                'urgent_surcharge_percent' => 40,
                'requirements' => ['Sampel sesuai standar dimensi ASTM', 'Minimal 5 specimen untuk statistik', 'Informasi jenis material'],
                'equipment_needed' => [19, 20],
                'sample_preparation' => 'Sampel harus berbentuk dogbone (tensile) atau flat surface (hardness). Follow ASTM specimen dimension.',
                'deliverables' => ['Stress-strain curve', 'Tensile strength', 'Elongation', 'Hardness value', 'Statistical analysis', 'Full test report'],
                'min_sample' => 5,
                'max_sample' => 50,
                'is_active' => true,
                'popularity' => 25,
            ],

            // MIKROBIOLOGI (3 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-MICRO-001',
                'name' => 'Uji Total Plate Count (TPC)',
                'description' => 'Penghitungan jumlah total mikroorganisme aerob dalam sampel.',
                'category' => 'mikrobiologi',
                'subcategory' => 'Microbial Analysis',
                'method' => 'SNI 2897-2008, APHA 9215',
                'duration_days' => 5,
                'price_internal' => 100000,
                'price_external_edu' => 150000,
                'price_external' => 200000,
                'urgent_surcharge_percent' => 30,
                'requirements' => ['Sampel dalam kondisi steril', 'Minimal 10 mL liquid atau 10 g solid', 'Tanpa preservative (jika mungkin)'],
                'equipment_needed' => [21, 22],
                'sample_preparation' => 'Sampel harus dalam container steril, disimpan 2-8°C, dan dianalisis <24 jam setelah sampling.',
                'deliverables' => ['Jumlah koloni (CFU/mL atau CFU/g)', 'Foto petri dish', 'Interpretasi hasil', 'Certificate of Analysis'],
                'min_sample' => 1,
                'max_sample' => 30,
                'is_active' => true,
                'popularity' => 58,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-MICRO-002',
                'name' => 'Uji Coliform dan E. coli',
                'description' => 'Deteksi dan enumerasi bakteri coliform dan E. coli sebagai indikator sanitasi.',
                'category' => 'mikrobiologi',
                'subcategory' => 'Water & Food Microbiology',
                'method' => 'SNI 2897-2008, APHA 9221',
                'duration_days' => 4,
                'price_internal' => 120000,
                'price_external_edu' => 180000,
                'price_external' => 240000,
                'urgent_surcharge_percent' => 30,
                'requirements' => ['Sampel air/makanan steril', 'Minimal 100 mL untuk air', 'Chain of custody form'],
                'equipment_needed' => [23],
                'sample_preparation' => 'Sampel dalam botol steril, hindari kontaminasi. Simpan 2-8°C, analisis <6 jam untuk air minum.',
                'deliverables' => ['MPN/100mL (Most Probable Number)', 'Coliform count', 'E. coli confirmation', 'Compliance statement', 'CoA'],
                'min_sample' => 1,
                'max_sample' => 25,
                'is_active' => true,
                'popularity' => 72,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-MICRO-003',
                'name' => 'Uji Aktivitas Antimikroba (Disc Diffusion)',
                'description' => 'Evaluasi aktivitas antimikroba ekstrak/senyawa terhadap bakteri patogen.',
                'category' => 'mikrobiologi',
                'subcategory' => 'Bioassay',
                'method' => 'Kirby-Bauer Disc Diffusion, CLSI M02',
                'duration_days' => 4,
                'price_internal' => 150000,
                'price_external_edu' => 225000,
                'price_external' => 300000,
                'urgent_surcharge_percent' => 40,
                'requirements' => ['Ekstrak/senyawa minimal 1 mL atau 500 mg', 'Informasi solvent', 'Target bakteri (3 strain included)'],
                'equipment_needed' => [24],
                'sample_preparation' => 'Ekstrak dalam solvent yang dapat di-aseptik (DMSO, ethanol, aqueous). Konsentrasi >10 mg/mL preferred.',
                'deliverables' => ['Diameter zona hambat', 'MIC (Minimum Inhibitory Concentration)', 'Kategori (sensitif/resistant)', 'Foto zone inhibition', 'Full report'],
                'min_sample' => 1,
                'max_sample' => 15,
                'is_active' => true,
                'popularity' => 44,
            ],

            // MATERIAL (2 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-MAT-001',
                'name' => 'Analisis BET Surface Area',
                'description' => 'Penentuan luas permukaan spesifik material menggunakan adsorpsi gas nitrogen.',
                'category' => 'material',
                'subcategory' => 'Surface Analysis',
                'method' => 'BET (Brunauer-Emmett-Teller) Method, ISO 9277',
                'duration_days' => 4,
                'price_internal' => 250000,
                'price_external_edu' => 375000,
                'price_external' => 500000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel powder minimal 500 mg', 'Sampel kering dan stabil', 'Informasi estimated surface area'],
                'equipment_needed' => [25],
                'sample_preparation' => 'Sampel harus di-degas untuk menghilangkan moisture dan adsorbate. Degassing 120-300°C, 3-12 jam.',
                'deliverables' => ['BET surface area (m²/g)', 'Isotherm plot', 'Pore size distribution', 'Pore volume', 'Full analysis report'],
                'min_sample' => 1,
                'max_sample' => 10,
                'is_active' => true,
                'popularity' => 31,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-MAT-002',
                'name' => 'Analisis TGA (Thermogravimetric Analysis)',
                'description' => 'Analisis perubahan massa material terhadap suhu untuk stabilitas termal.',
                'category' => 'material',
                'subcategory' => 'Thermal Analysis',
                'method' => 'ASTM E1131, ISO 11358',
                'duration_days' => 3,
                'price_internal' => 180000,
                'price_external_edu' => 270000,
                'price_external' => 360000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel 5-20 mg', 'Informasi komposisi material', 'Rentang suhu analisis yang diinginkan'],
                'equipment_needed' => [26],
                'sample_preparation' => 'Sampel harus kering dan homogen. Untuk polymer, gunakan 10-15 mg. Untuk komposit, 15-20 mg.',
                'deliverables' => ['TGA curve', 'DTG (Derivative) curve', 'Decomposition temperature', 'Residue analysis', 'Full report'],
                'min_sample' => 1,
                'max_sample' => 20,
                'is_active' => true,
                'popularity' => 27,
            ],

            // LINGKUNGAN (2 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-ENV-001',
                'name' => 'Analisis Kualitas Air (pH, DO, BOD, COD)',
                'description' => 'Paket lengkap analisis parameter kualitas air untuk monitoring lingkungan.',
                'category' => 'lingkungan',
                'subcategory' => 'Water Quality',
                'method' => 'SNI 06-6989 series, APHA Standard Methods',
                'duration_days' => 5,
                'price_internal' => 300000,
                'price_external_edu' => 450000,
                'price_external' => 600000,
                'urgent_surcharge_percent' => 40,
                'requirements' => ['Sampel air minimal 2 L dalam botol steril', 'Preservasi sesuai parameter', 'Data lokasi sampling'],
                'equipment_needed' => [27, 28],
                'sample_preparation' => 'BOD sampel harus segar (<6 jam). COD dapat dipreservasi dengan H2SO4. DO diukur on-site lebih baik.',
                'deliverables' => ['Hasil semua parameter', 'Perbandingan dengan baku mutu', 'Interpretasi kualitas air', 'Rekomendasi', 'Certificate of Analysis'],
                'min_sample' => 1,
                'max_sample' => 15,
                'is_active' => true,
                'popularity' => 53,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-ENV-002',
                'name' => 'Analisis Logam Berat dalam Tanah',
                'description' => 'Penentuan konsentrasi logam berat (Pb, Cd, Hg, As, Cr) dalam sampel tanah.',
                'category' => 'lingkungan',
                'subcategory' => 'Soil Analysis',
                'method' => 'EPA 3050B, EPA 6010D',
                'duration_days' => 7,
                'price_internal' => 350000,
                'price_external_edu' => 525000,
                'price_external' => 700000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel tanah minimal 500 g', 'Informasi lokasi dan kedalaman sampling', 'Chain of custody'],
                'equipment_needed' => [29],
                'sample_preparation' => 'Sampel dikeringkan udara, diayak <2 mm, homogenkan. Destruksi dengan asam kuat sebelum analisis.',
                'deliverables' => ['Konsentrasi logam berat (mg/kg)', 'Perbandingan dengan PP tentang tanah', 'Tingkat pencemaran', 'Full report', 'CoA'],
                'min_sample' => 1,
                'max_sample' => 12,
                'is_active' => true,
                'popularity' => 37,
            ],

            // PANGAN (2 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-FOOD-001',
                'name' => 'Analisis Proksimat (Protein, Lemak, Air, Abu)',
                'description' => 'Analisis komposisi kimia dasar bahan pangan secara lengkap.',
                'category' => 'pangan',
                'subcategory' => 'Nutritional Analysis',
                'method' => 'AOAC Official Methods, SNI 01-2891',
                'duration_days' => 5,
                'price_internal' => 250000,
                'price_external_edu' => 375000,
                'price_external' => 500000,
                'urgent_surcharge_percent' => 40,
                'requirements' => ['Sampel pangan minimal 500 g', 'Sampel segar atau informasi storage', 'Komposisi bahan (jika processed food)'],
                'equipment_needed' => [30, 31],
                'sample_preparation' => 'Sampel dihomogenisasi. Untuk solid, grind sampai halus. Simpan frozen jika tidak langsung dianalisis.',
                'deliverables' => ['Kadar air (%)', 'Kadar abu (%)', 'Kadar protein (%)', 'Kadar lemak (%)', 'Karbohidrat (by difference)', 'Full report'],
                'min_sample' => 1,
                'max_sample' => 20,
                'is_active' => true,
                'popularity' => 46,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-FOOD-002',
                'name' => 'Uji Cemaran Mikroba Pangan (TPC, Coliform, E.coli, Salmonella)',
                'description' => 'Paket lengkap analisis cemaran mikrobiologi untuk keamanan pangan.',
                'category' => 'pangan',
                'subcategory' => 'Food Safety',
                'method' => 'SNI 2897-2008, BAM FDA',
                'duration_days' => 7,
                'price_internal' => 300000,
                'price_external_edu' => 450000,
                'price_external' => 600000,
                'urgent_surcharge_percent' => 30,
                'requirements' => ['Sampel pangan minimal 300 g dalam kondisi steril', 'Informasi produk dan storage', 'Best before date'],
                'equipment_needed' => [32],
                'sample_preparation' => 'Sampel dalam packaging asli atau bag steril. Hindari kontaminasi. Simpan suhu sesuai produk.',
                'deliverables' => ['TPC (CFU/g)', 'Coliform (MPN/g)', 'E.coli (MPN/g)', 'Salmonella (presence/absence)', 'Compliance dengan SNI', 'Certificate'],
                'min_sample' => 1,
                'max_sample' => 15,
                'is_active' => true,
                'popularity' => 64,
            ],

            // FARMASI (2 services)
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-PHARM-001',
                'name' => 'Penetapan Kadar Bahan Aktif Obat (Assay)',
                'description' => 'Penentuan kadar zat aktif dalam sediaan farmasi menggunakan HPLC/Spektrofotometri.',
                'category' => 'farmasi',
                'subcategory' => 'Drug Analysis',
                'method' => 'USP Monograph, Farmakope Indonesia',
                'duration_days' => 5,
                'price_internal' => 250000,
                'price_external_edu' => 375000,
                'price_external' => 500000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel sediaan minimal 20 tablet/kapsul atau 50 mL liquid', 'Informasi zat aktif dan klaim kadar', 'Standar pembanding (jika tersedia)'],
                'equipment_needed' => [33],
                'sample_preparation' => 'Sampel ditimbang/diukur, diekstraksi sesuai monograph. Untuk tablet, diserbukkan dan homogenkan.',
                'deliverables' => ['Kadar zat aktif (%)', 'Compliance dengan Farmakope', 'Chromatogram/Spektra', 'Validasi metode', 'Certificate of Analysis'],
                'min_sample' => 1,
                'max_sample' => 15,
                'is_active' => true,
                'popularity' => 42,
            ],
            [
                'laboratory_id' => $laboratories->random()->id,
                'code' => 'SVC-PHARM-002',
                'name' => 'Uji Disolusi Tablet/Kapsul',
                'description' => 'Evaluasi profil pelepasan zat aktif dari sediaan solid farmasi.',
                'category' => 'farmasi',
                'subcategory' => 'Pharmaceutical QC',
                'method' => 'USP <711>, Farmakope Indonesia Ed. VI',
                'duration_days' => 4,
                'price_internal' => 200000,
                'price_external_edu' => 300000,
                'price_external' => 400000,
                'urgent_surcharge_percent' => 50,
                'requirements' => ['Sampel minimal 18 tablet/kapsul', 'Informasi media disolusi (jika ada)', 'Waktu sampling yang diinginkan'],
                'equipment_needed' => [34],
                'sample_preparation' => 'Tablet/kapsul harus dalam kondisi baik (tidak pecah, tidak expired). Simpan sesuai kondisi penyimpanan label.',
                'deliverables' => ['Profil disolusi (% vs time)', 'Q value pada waktu tertentu', 'Grafik disolusi', 'Compliance USP', 'Full validation report'],
                'min_sample' => 18,
                'max_sample' => 30,
                'is_active' => true,
                'popularity' => 33,
            ],
        ];

        foreach ($services as $serviceData) {
            Service::create($serviceData);
        }

        $this->command->info('✓ Successfully seeded ' . count($services) . ' services across 8 categories!');
    }
}
